### ISSUE TITLE
Writer需要关闭才会把数据写完整

### ISSUE THREAD

**Issue by xxxsen** [nicholastoddsmith/aesrw#2]
这个会有一个问题, A server往B server写数据, 等待B server回复消息, 但是A要关闭writer才会把数据写完, 这个会导致一直等待下去。

**Comment by nogilnick** [comment]
如果你把writer关闭了，还有没有问题？

**Comment by xxxsen** [comment]
把writer关闭了是正常的, 但正常来说, 不应该在关闭的时候还写数据啊。

**Comment by nogilnick** [comment]
那如果server A没有把writer关闭，server B怎么可以知道server A写完呢？这个问题很难解决。我觉得你就把那个writer关闭了就行了。如果server A再一次要往server B写数据，你就要从头开始。如果你有更好的办法，你可以做一个pull request. 你把writer关闭了，我把你的issue关闭。 谢谢
