### ISSUE TITLE
嘿嘿, 不考虑自定义reader/writer的输出数据格式吗？

### ISSUE THREAD

**Issue by xxxsen** [nicholastoddsmith/aesrw#3]
看了你的代码, 需要在close的时候写数据是因为cbc要求输入的数据是block长度的整数倍, 这样的话, 如果别人用了你的writer那么他就需要关注自己的数据是否是block长度的倍数, 考虑在网络场景下, 假设用户有自定义的数据格式, 那么他在封装完自己的数据后还需要再手动pad下数据, 否则他的包写进去后对端根本就收不到, 因为部分数据不满足block的整数倍, 需要close的时候才会写, 这样对使用者来说是很蛋疼的。如果在write数据的时候就自动补位并加入数据长度, 这样子就不需要在close的时候写数据了。 刚好最近也写了类似的代码, 就来看下老哥你的repo了。

**Comment by nogilnick** [comment]
Yes, adding the length is one way to handle it. However, that way you need to read the data twice. Once to get the length and then another time to actually encrypt it putting the length first. The padding method is more efficient, it is why I chose it, and I don't have any plans to change it. I wrote this library with file I/O in mind. It just happens to work for sockets as well.
